---

# httpd is handled by the base-apache role upstream
- name: Install php and git 
  action: apt pkg={{ item }} state=installed
  with_items:
   - php5
   - php5-mysql
   - git

#- name: Configure SELinux to allow httpd to connect to remote database
#  seboolean: name=httpd_can_network_connect_db state=true persistent=yes
#  when: sestatus.rc != 0

- name: Copy the code from repository
  git: repo={{ repository }} dest=/var/www/html/
