---
# This role will install MySQL and create db user and give permissions.

- name: Install Mysql package
  apt: pkg={{ item }} state=present
  with_items:
   - mysql-server
   - mysql-client
   - php5-mysql
   #- libsemanage-python

#- name: Configure SELinux to start mysql on any port
#  seboolean: name=mysql_connect_any state=true persistent=yes
#  when: sestatus.rc != 0

- name: Create Mysql configuration file
  template: src=my.cnf.j2 dest=/etc/my.cnf
  notify: 
  - restart mysql

- name: Start Mysql Service
  action: service name=mysqld state=started enabled=true

- name: Create Application Database
  mysql_db: name={{ dbname }} state=present

- name: Create Application DB User
  mysql_user: name={{ dbuser }} password={{ upassword }} priv=*.*:ALL host='%' state=present
